### ISSUE TITLE
Allegorihmic version of unreal doesnot exist 

### ISSUE THREAD

**Issue by akhil22** [deepdrive/deepdrive-sim#2]
Hi,
I am trying to clone the Allegorithmic version of unreal as suggested in your ReadMe file but I am getting page not found error !! Would deep drive work with official version of Unreal Engine ?

**Comment by crizCraig** [comment]
Hi @akhil22 - have you [joined Epic's GitHub org](https://www.unrealengine.com/en-US/ue4-on-github)?

**Comment by akhil22** [comment]
Yeah I did but then I cloned their version of Unreal Engine. Let me try cloning the Allegorithmic version.

**Comment by akhil22** [comment]
Its working now !!. Thanks for your reply.

**Comment by crizCraig** [comment]
Glad to hear it!
