### ISSUE TITLE
Support on windows?

### ISSUE THREAD

**Issue by philippbb** [deepdrive/deepdrive-sim#31]
Hi,

Thank you very much for this project.

I managed to set it up with some with 4.21 on windows, but only for local car AI and manual driving.

So I am a bit confused if this is still possible on windows to test autonomous driving because on github on one of the branches its written its supported but on the documentation as well as in main deepdrive repository its written its not.

Maybe I just dont understand the github documentation part where it says: "Set your python bin"

Is the DeepDriveSim apparently runs on windows, but the DeepDrive python part is not supported anymore on windows?

Thank you again for the cool project and the cool KITT movies on youtube :)

**Comment by philippbb** [comment]
ok its moving :) i thought I need 2.7 for this, but 3.6.8 did work for small test. thank you.

**Comment by crizCraig** [comment]
Hi @philippbb - you're right in that the latest Deepdrive does not support Windows. Sorry about this! It is possible to run the development setup on Windows, though it requires a little more work.

https://simdocs.deepdrive.io/docs/setup/windows
